name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Bitcoin node
        id: bitcoin-cache
        uses: actions/cache@v2
        with:
          path: ~/bitcoin
          key: ${{ runner.os }}-cache

      - name: Download Bitcoin node
        if: steps.bitcoin-cache.outputs.cache-hit != 'true'
        run: |
          wget -P ~/bitcoin https://bitcoin.org/bin/bitcoin-core-0.20.0/bitcoin-0.20.0-x86_64-linux-gnu.tar.gz

      - name: Start Bitcoin node
        run: |
          cd ~/bitcoin
          tar -xvf bitcoin-0.20.0-x86_64-linux-gnu.tar.gz
          cp bitcoin-0.20.0/bin/* /usr/local/bin/
          bitcoind -reindex -txindex -regtest -daemon -rpcport=18443 -rpcuser=bitcoin -rpcpassword=local321 -deprecatedrpc=signrawtransaction -fallbackfee=0.00001 -addresstype=p2sh-segwit -zmqpubrawblock=tcp://127.0.0.1:29000 -zmqpubrawtx=tcp://127.0.0.1:29000
          sleep 5
          bitcoin-cli -regtest -rpcport=18443 -rpcuser=bitcoin -rpcpassword=local321 generatetoaddress 101 $(bitcoin-cli -regtest -rpcport=18443 -rpcuser=bitcoin -rpcpassword=local321 getnewaddress '' 'bech32')

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: restore lerna node_modules from cache
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          path: |
            node_modules
            */*/node_modules

      - name: yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - run: yarn bootstrap

      - run: yarn build
      - run: yarn test

      - name: Get test coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
